### ISSUE TITLE
Eng Service Design

### ISSUE THREAD

**Issue by xinbenlv** [zgzgorg/zgthx#2]
## Model Design (fields and behaviors)
```
ZgUserProfile
 - id: string UUID
 - role: ENUM
 - email: string
 - fullname: string

ZgWallet:
 - id:string UUID
 - ownerId: string(ZgUserProfile.id) [co-index tokenSimble+ownerId]
 - tokenSimbol: string [co-index tokenSimble+ownerId]
 - currentBalance: amount
 - lastestTxId: string(ZgTransactionEntry.id) # TODO think about it.

ZgUserAuth (TODO use Auth0)

ZgTransactionEntry (each transaction will have 2 entries, a > b 100 will show a - 100 with b, b -100 
 - id: string [UUID]
 - ownerId: string [Index]
 - timestamp: datetime [Index nonunique]
 - counterpartId: string(ZgUser)
 - tokenSimbol: string
 - amount: number(+ for receiving, - for sending) 

ZgBenefit


```
